# Generated by Django 5.1.1 on 2024-10-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_bank_admin_user',
            field=models.BooleanField(default=False),
        ),
    ]
