# Generated by Django 5.1.1 on 2024-10-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanconfig',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.07, max_digits=2),
        ),
        migrations.AlterField(
            model_name='loanconfig',
            name='max_loan_amount',
            field=models.DecimalField(decimal_places=2, default=1000000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanconfig',
            name='max_loan_duration',
            field=models.PositiveIntegerField(default=36),
        ),
        migrations.AlterField(
            model_name='loanconfig',
            name='min_loan_amount',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanconfig',
            name='min_loan_duration',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
