# Generated by Django 5.1.1 on 2024-10-01 11:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loanconfig_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='total_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='amortizationschedule',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortization', to='loans.loan'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanconfig',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.07'), max_digits=10),
        ),
    ]
